name: Manual Deployment Workflow

on:
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Select target branch for deployment'
        required: true
        default: 'staging_fix'
        type: choice
        options:
          - staging_fix
          - staging_production

jobs:
  validate-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Target Branch
        run: |
          TARGET_BRANCH="${{ github.event.inputs.target_branch }}"
          HEAD_BRANCH="${GITHUB_REF#refs/heads/}"

          echo "Head branch: $HEAD_BRANCH"
          echo "Target branch: $TARGET_BRANCH"

          # # Check if the selected target branch is valid
          # if [[ "$TARGET_BRANCH" != "staging_fix" && "$TARGET_BRANCH" != "staging_production" ]]; then
          #   echo "❌ Error: Invalid target branch selected ($TARGET_BRANCH). Allowed: staging_fix, staging_production."
          #   exit 1
          # fi

          echo "✅ Branch validation successful. Proceeding..."

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Linting
        run: npm run lint
        shell: bash
    
  tests_coverage:
    needs: lint
    name: Test Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
