name: Manual Deployment Workflow

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select branch to deploy'
        required: true
        default: 'staging_fix'
        type: choice
        options:
          - staging_fix
          - staging_production

jobs:
  validate-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Selected Branch
        run: |
          BRANCH="${{ github.event.inputs.branch }}"
          if [[ "$BRANCH" == "staging_fix" || "$BRANCH" == "staging_production" ]]; then
            echo "Valid branch selected. Proceeding with deployment..."
          else
            echo "Error: Invalid branch selected ($BRANCH). Exiting workflow."
            exit 1
          fi

  deploy:
    needs: validate-branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy Code
        run: |
          echo "Deploying from branch ${{ github.event.inputs.branch }} to staging environment..."
          # Add your deployment script or commands here
